services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - DATABASE_NAME=${DATABASE_NAME:-chat_store}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      
      # Redis Configuration
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      
      # API Configuration
      - API_KEY=${API_KEY:-your-secret-api-key-here}
      - API_V1_STR=/api/v1
      
      # Rate Limiting Configuration
      - RATE_LIMITER_ENABLED=${RATE_LIMITER_ENABLED:-false}
      - RATE_LIMITER_MAX_REQUESTS=${RATE_LIMITER_MAX_REQUESTS:-100}
      - RATE_LIMITER_TIMEFRAME=${RATE_LIMITER_TIMEFRAME:-60}
      - RATE_LIMIT_CREATE_SESSION=${RATE_LIMIT_CREATE_SESSION:-10/minute}
      - RATE_LIMIT_LIST_SESSIONS=${RATE_LIMIT_LIST_SESSIONS:-30/minute}
      - RATE_LIMIT_CREATE_MESSAGE=${RATE_LIMIT_CREATE_MESSAGE:-50/minute}
      - RATE_LIMIT_GET_MESSAGES=${RATE_LIMIT_GET_MESSAGES:-100/minute}
      - RATE_LIMIT_RESUME_MESSAGE=${RATE_LIMIT_RESUME_MESSAGE:-5/minute}
      - RATE_LIMIT_UPDATE_SESSION=${RATE_LIMIT_UPDATE_SESSION:-20/minute}
      - RATE_LIMIT_DELETE_SESSION=${RATE_LIMIT_DELETE_SESSION:-10/minute}
      - RATE_LIMIT_TOGGLE_FAVORITE=${RATE_LIMIT_TOGGLE_FAVORITE:-20/minute}
      
      # CORS Configuration
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS:-http://localhost:3000,http://localhost:8080,http://localhost:8000}
      
      # Debug Configuration
      - DEBUG=${DEBUG:-false}
    depends_on:
      - db
      - redis
    volumes:
      - ./tests:/app/tests
    command: uvicorn chat_store.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-chat_store}
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    ports:
      - "5379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "8090:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:Sharlin
  default:
    name: chat_store_network